### PR TITLE
Add review for 219

### PR DESCRIPTION
**Pull request by ebu060**

### CODE REVIEW

**Review by mrkara — CHANGES_REQUESTED** [review]
Please adhere to the directory structure of the repo. You are missing the directory of the milestone. It should be something like `/Reviews/219 - Casper Analytics - iOS/5 - Integrate Casper Signer/README.md`

**Comment by ebu060** [comment]
> Please adhere to the directory structure of the repo. You are missing the directory of the milestone. It should be something like `/Reviews/219 - Casper Analytics - iOS/5 - Integrate Casper Signer/README.md`


Directory structure edited.

**Comment by ebu060** [comment]
Directory structure edited.

**Review by mrkara — APPROVED** [review]
Well done. Thanks!

**Review by mssteuer — APPROVED** [review]

**Review by wulfkaal — COMMENTED** [review]
Thx

**Pull request merged**
